"""Add question and response columns to Session model

Revision ID: 62fdc2f4d5d0
Revises: 
Create Date: 2025-06-04 01:58:32.386833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62fdc2f4d5d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('response', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('response')
        batch_op.drop_column('question')

    # ### end Alembic commands ###
